services:
  _defaults:
    public: true
    autowire: true

  ICanBoogie\Routing\RequestResponderProvider:
    tags:
    - { name: request_responder }

  ICanBoogie\Routing\ActionResponderProvider:
    class: ICanBoogie\Routing\ActionResponderProvider\Mutable

  ICanBoogie\Routing\RouteProvider:
    factory: [ ICanBoogie\Binding\Routing\Hooks, get_routes ]

  ICanBoogie\Routing\UrlGenerator: ~

# HTTP

  ICanBoogie\HTTP\ResponderProvider:
    class: ICanBoogie\HTTP\ResponderProvider\Chain
    arguments:
      $chain: !tagged_iterator { tag: request_responder }
