parameters:
  routing.action_responder.aliases: ~ # provided by the compiler pass

services:
  _defaults:
    autowire: true

  ICanBoogie\Routing\ActionResponderProvider:
    class: ICanBoogie\Routing\ActionResponderProvider\Container
    arguments:
    - !tagged_locator { tag: action_responder }
    - '%routing.action_responder.aliases%'

  ICanBoogie\Routing\RequestResponderProvider:
    tags:
    - { name: request_responder }

  ICanBoogie\Routing\IterableRouteProvider:
    factory: [ ICanBoogie\Binding\Routing\Hooks, get_routes ]

  ICanBoogie\Routing\RouteProvider:
    alias: ICanBoogie\Routing\IterableRouteProvider

  ICanBoogie\Routing\RouteProvider\Memoize:
    decorates: ICanBoogie\Routing\IterableRouteProvider

  ICanBoogie\Routing\UrlGenerator:
    public: true
